import sys
import os
import asyncio
from unittest.mock import MagicMock, patch

# Mock google.generativeai BEFORE importing analyzer_agent
mock_genai = MagicMock()
sys.modules["google.generativeai"] = mock_genai

# Add parent directory to path to import analyzer_agent
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import after mocking
from analyzer_agent import AnalyzerAgent

async def test_gemini_summary():
    print("Starting Gemini integration test...")
    
    # Setup environment variables
    with patch.dict(os.environ, {"ANALYSIS_MODEL": "gemini", "GEMINI_API_KEY": "fake_key"}):
        # Initialize agent
        agent = AnalyzerAgent()
        
        # Mock the model instance explicitly if __init__ didn't pick it up (due to how we mocked genai)
        # But our mock_genai.GenerativeModel(...) should return a mock object.
        # Let's verify agent.gemini_model exists
        if not hasattr(agent, 'gemini_model'):
            print("Error: agent.gemini_model not initialized")
            return

        # Mock the response from generate_content_async
        mock_response = MagicMock()
        mock_response.text = "This is a summary.\nIt has multiple lines.\nGenerated by Gemini."
        
        # Setup the async return value for generate_content_async
        future = asyncio.Future()
        future.set_result(mock_response)
        agent.gemini_model.generate_content_async.return_value = future
        
        # Execute
        title = "Test Title"
        content = "Test Content " * 100
        print(f"Testing generate_summary with model={agent.analysis_model}")
        
        summary = await agent.generate_summary(title, content)
        
        # Verify
        print(f"Generated Summary:\n{summary}")
        
        # Check if configure was called
        mock_genai.configure.assert_called_with(api_key="fake_key")
        print("Verified: genai.configure called with api_key")
        
        # Check if generate_content_async was called
        agent.gemini_model.generate_content_async.assert_called_once()
        print("Verified: generate_content_async called")
        
        # Verify arguments
        args = agent.gemini_model.generate_content_async.call_args[0]
        prompt_arg = args[0]
        assert title in prompt_arg
        # assert content[:50] in prompt_arg # Content might be truncated or formatted
        
        print("Test Passed Successfully!")

if __name__ == "__main__":
    asyncio.run(test_gemini_summary())
