import sys
import os
import asyncio
from unittest.mock import MagicMock, patch

# Mock google.genai BEFORE importing analyzer_agent
mock_genai = MagicMock()
mock_google = MagicMock()
mock_google.genai = mock_genai
sys.modules["google"] = mock_google
sys.modules["google.genai"] = mock_genai
sys.modules["google.genai.types"] = MagicMock()

# Add parent directory to path to import analyzer_agent
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import after mocking
from analyzer_agent import AnalyzerAgent

async def test_gemini_v1_integration():
    print("Starting Gemini v1 integration test...")
    
    # Setup environment variables
    with patch.dict(os.environ, {"ANALYSIS_MODEL": "gemini", "GEMINI_API_KEY": "fake_key"}):
        # Mock the client instance
        mock_client = MagicMock()
        mock_genai.Client.return_value = mock_client
        
        # Initialize agent
        agent = AnalyzerAgent()
        
        # Verify client initialization
        mock_genai.Client.assert_called_with(api_key="fake_key")
        assert agent.gemini_client == mock_client
        print("Verified: Client initialized with api_key")

        # Mock the response from generate_content
        mock_response = MagicMock()
        mock_response.text = "This is a summary.\nIt has multiple lines.\nGenerated by Gemini v1."
        
        # Setup the async return value for aio.models.generate_content
        future = asyncio.Future()
        future.set_result(mock_response)
        mock_client.aio.models.generate_content.return_value = future
        
        # Execute
        title = "Test Title"
        content = "Test Content " * 100
        print(f"Testing generate_summary with model={agent.analysis_model}")
        
        summary = await agent.generate_summary(title, content)
        
        # Verify
        print(f"Generated Summary:\n{summary}")
        
        # Check if generate_content was called
        mock_client.aio.models.generate_content.assert_called_once()
        print("Verified: generate_content called")
        
        # Verify arguments
        args, kwargs = mock_client.aio.models.generate_content.call_args
        assert kwargs['model'] == 'gemini-2.0-flash'
        assert title in kwargs['contents']
        
        print("Test Passed Successfully!")

if __name__ == "__main__":
    asyncio.run(test_gemini_v1_integration())
